pull_request_rules:
  - name: automatic merge for Greenkeeper pull requests
    conditions:
      - status-success=Travis CI - Pull Request
      - status-success=security/snyk - package.json
    actions:
      merge:
        method: merge
