dist: trusty
sudo: false
language: node_js
node_js:
  - 6
cache:
  directories:
     - ./node_modules
branches:
  only:
    - master
notifications:
  email: false    
install:
  - npm install
script:
  - echo "Everything is working great. Cool!"
