dist: trusty
language: node_js
node_js:
  - node
cache:
  directories:
    - node_modules
branches:
  only:
    - master
    - /^snyk/.*$/
notifications:
  email: false   
before_install:
  - "npm i -g npm@latest"
install:
  - npm install
script:
  - echo "Everything is working great. Cool!"
