dist: trusty
sudo: false
language: node_js
node_js:
  - 7
cache:
  directories:
     - node_modules     
branches:
  only:
    - master
    - /^greenkeeper/.*$/
notifications:
  email: false    
install:
  - npm install
script:
  - echo "Everything is working great. Cool!"
